Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Repo   = "LalbaAnthony/antho-common-shell"
$Branch = "main"

$SrcUrl      = "https://raw.githubusercontent.com/$Repo/$Branch/src/pwsh"
$ManifestUrl = "$SrcUrl/manifest.txt"
$ExtraFile   = Join-Path $HOME "profile_extra.ps1"

$ProfileFile = $PROFILE
$ProfileHook = 'if (Test-Path "$HOME\profile_extra.ps1") { . "$HOME\profile_extra.ps1" }'

function Get-RemoteText {
    param([Parameter(Mandatory)] [string] $Uri)

    # Not .Content: that is a string for a text/* response and a byte[] for
    # anything else, so it would make the result depend on the server's
    # Content-Type header. The raw bytes are UTF-8 whatever the header claims.
    $stream = (Invoke-WebRequest -Uri $Uri -UseBasicParsing).RawContentStream
    $text = [System.Text.Encoding]::UTF8.GetString($stream.ToArray())

    # A part saved with a BOM would otherwise splice U+FEFF into the middle of
    # the concatenation, where PowerShell treats it as a stray token.
    return $text.TrimStart([char]0xFEFF)
}

function Get-Extra {
    Write-Host "Fetching manifest from $ManifestUrl..."
    $manifest = Get-RemoteText -Uri $ManifestUrl

    # Drop comments and blanks; Trim() also absorbs the CR of a CRLF manifest.
    $parts = @(
        $manifest -split "`n" |
            ForEach-Object { ($_ -split '#')[0].Trim() } |
            Where-Object { $_ }
    )

    if ($parts.Count -eq 0) {
        throw "Manifest listed no files, aborting."
    }

    $chunks = New-Object System.Collections.Generic.List[string]
    $chunks.Add(
        "# Generated by antho-common-shell from $Repo@$Branch.`n" +
        "# Do not edit: change src/pwsh/*.ps1 in the repo, then re-run 'cshupd'."
    )

    foreach ($part in $parts) {
        Write-Host "  + $part"
        $content = Get-RemoteText -Uri "$SrcUrl/$part"

        # Normalise to LF - the bytes GitHub serves for these parts - and strip
        # the trailing newlines so the join controls the separator exactly.
        $chunks.Add((($content -replace "`r`n", "`n").TrimEnd("`n")))
    }

    Write-Host "Writing $($parts.Count) part(s) to $ExtraFile..."

    # Written in one shot, after every part has downloaded: a failure partway
    # through must not leave a truncated profile behind for $PROFILE to source.
    $body = ($chunks -join "`n`n") + "`n"
    Set-Content -Path $ExtraFile -Value $body -Encoding UTF8 -NoNewline
}

function Register-InProfile {
    if (-not (Test-Path $ProfileFile)) {
        New-Item -Path $ProfileFile -ItemType File -Force | Out-Null
    }

    $content = Get-Content -Path $ProfileFile -Raw -ErrorAction SilentlyContinue
    if ($content -and $content.Contains("profile_extra.ps1")) {
        Write-Host "Hook already present in $ProfileFile, skipping."
    } else {
        Write-Host "Registering hook in $ProfileFile..."
        Add-Content -Path $ProfileFile -Value ""
        Add-Content -Path $ProfileFile -Value $ProfileHook
    }
}

function Invoke-ProfileReload {
    Write-Host "Reloading profile..."
    # dot-sourcing may not propagate to the parent shell when run via iex
    . $ProfileFile
}

function Main {
    Get-Extra
    Register-InProfile
    Invoke-ProfileReload
    Write-Host "PowerShell extra installed successfully!"
}

Main
