#!/bin/bash

set -euo pipefail

REPO="LalbaAnthony/antho-common-shell"
BRANCH="main"

SRC_URL="https://raw.githubusercontent.com/${REPO}/${BRANCH}/src/bash"
MANIFEST_URL="${SRC_URL}/manifest.txt"
EXTRA_FILE="$HOME/.bashrc_extra"

BASHRC_FILE="$HOME/.bashrc"
BASHRC_HOOK='[ -f ~/.bashrc_extra ] && . ~/.bashrc_extra'

# Set while the concatenation is in flight, cleared once it lands.
TMP_FILE=""

cleanup() {
    if [ -n "$TMP_FILE" ]; then
        rm -f "$TMP_FILE"
    fi
}
trap cleanup EXIT

download_extra() {
    echo "Fetching manifest from $MANIFEST_URL..."
    local manifest
    manifest="$(curl -fsSL "$MANIFEST_URL")"

    # Built next to the target so the final mv is a rename on the same
    # filesystem, and so a failed part download can never leave a truncated
    # ~/.bashrc_extra behind for ~/.bashrc to source.
    TMP_FILE="$(mktemp "${EXTRA_FILE}.XXXXXX")"

    {
        echo "# Generated by antho-common-shell from ${REPO}@${BRANCH}."
        echo "# Do not edit: change src/bash/*.sh in the repo, then re-run 'cshupd'."
        echo ""
    } > "$TMP_FILE"

    local part count=0
    while IFS= read -r part || [ -n "$part" ]; do
        # Strip comments, then all whitespace - which also absorbs the CR of a
        # CRLF manifest. Part names are filenames and carry no spaces.
        part="${part%%#*}"
        part="$(printf '%s' "$part" | tr -d '[:space:]')"
        [ -n "$part" ] || continue

        echo "  + ${part}"
        curl -fsSL "${SRC_URL}/${part}" >> "$TMP_FILE"

        # Separator, and a safety net for a part with no trailing newline.
        printf '\n' >> "$TMP_FILE"

        count=$((count + 1))
    done <<< "$manifest"

    if [ "$count" -eq 0 ]; then
        echo "Manifest listed no files, aborting." >&2
        return 1
    fi

    echo "Writing $count part(s) to $EXTRA_FILE..."
    chmod 644 "$TMP_FILE"   # mktemp creates 0600
    mv -f "$TMP_FILE" "$EXTRA_FILE"
    TMP_FILE=""
}

register_in_bashrc() {
    if grep -qxF "$BASHRC_HOOK" "$BASHRC_FILE"; then
        echo "Hook already present in $BASHRC_FILE, skipping."
    else
        echo "Registering hook in $BASHRC_FILE..."
        echo "" >> "$BASHRC_FILE"
        echo "$BASHRC_HOOK" >> "$BASHRC_FILE"
    fi
}

reload_shell() {
    echo "Reloading shell..."
    # source may not propagate to the parent shell when run via curl | bash
    # shellcheck disable=SC1090
    source "$BASHRC_FILE" || true
}

main() {
    download_extra
    register_in_bashrc
    reload_shell
    echo "Bash extra installed successfully!"
}

main
